@UrlShortenerAPI_HostAddress = http://localhost:5251

### Shorten a URL
POST {{UrlShortenerAPI_HostAddress}}/api/urls
Content-Type: application/json

{
  "originalUrl": "https://www.example.com/your-long-url"
}

### Retrieve Original URL
GET {{UrlShortenerAPI_HostAddress}}/api/urls/{shortCode}
Accept: application/json
